-- Drift Club : catalogue des livrées qui sortent des caisses (GÉNÉRÉ, ne pas modifier à la main).
-- Produit par : npx vite-node tools/gen-catalogue-sql.ts (à partir de src/core/skins.ts et fumees.ts).
-- À coller dans Supabase → SQL Editor → Run, après 0005. Peut être relancé sans danger.
-- Après avoir ajouté ou retiré des livrées ou des fumées : relancer le générateur et coller de nouveau ce fichier.
-- Les fumées de pneus y figurent sous la voiture « fumee » ; elles sortent des mêmes caisses que les livrées.
-- 251 objets (livrées et fumées).

insert into public.catalogue_skins (voiture, id, rarete) values
  ('break', 'rayures', 'commune'),
  ('break', 'bicolore', 'commune'),
  ('break', 'filet', 'commune'),
  ('break', 'vacances', 'commune'),
  ('break', 'portieres', 'commune'),
  ('break', 'riviera', 'commune'),
  ('break', 'polka', 'commune'),
  ('break', 'peinture', 'commune'),
  ('break', 'zebre', 'commune'),
  ('break', 'n1', 'commune'),
  ('break', 'sakura', 'commune'),
  ('break', 'boiseries', 'rare'),
  ('break', 'courrier', 'rare'),
  ('break', 'dalmatiens', 'rare'),
  ('break', 'taxi', 'rare'),
  ('break', 'mystere', 'rare'),
  ('break', 'fantomes', 'rare'),
  ('break', 'tofu', 'rare'),
  ('break', 'urgences', 'rare'),
  ('break', 'n42', 'rare'),
  ('break', 'touge', 'epique'),
  ('break', 'safari', 'epique'),
  ('break', 'rouille', 'epique'),
  ('break', 'toutvabien', 'epique'),
  ('break', 'eurobeat', 'epique'),
  ('break', 'codevert', 'epique'),
  ('break', 'flammes', 'legendaire'),
  ('break', 'delorean', 'legendaire'),
  ('break', 'voielactee', 'legendaire'),
  ('break', 'or', 'exotique'),
  ('break', 'famille', 'exotique'),
  ('equilibree', 'rayures', 'commune'),
  ('equilibree', 'bicolore', 'commune'),
  ('equilibree', 'lisere', 'commune'),
  ('equilibree', 'panda', 'commune'),
  ('equilibree', 'diagonales', 'commune'),
  ('equilibree', 'riviera', 'commune'),
  ('equilibree', 'polka', 'commune'),
  ('equilibree', 'kawaii', 'commune'),
  ('equilibree', 'danger', 'commune'),
  ('equilibree', 'huitbits', 'commune'),
  ('equilibree', 'peinture', 'commune'),
  ('equilibree', 'n404', 'commune'),
  ('equilibree', 'course', 'rare'),
  ('equilibree', 'carbone', 'rare'),
  ('equilibree', 'damier', 'rare'),
  ('equilibree', 'pois', 'rare'),
  ('equilibree', 'nyan', 'rare'),
  ('equilibree', 'tigre', 'rare'),
  ('equilibree', 'mystere', 'rare'),
  ('equilibree', 'urgences', 'rare'),
  ('equilibree', 'dejavu', 'rare'),
  ('equilibree', 'n42', 'rare'),
  ('equilibree', 'touge', 'epique'),
  ('equilibree', 'vitesse', 'epique'),
  ('equilibree', 'camo', 'epique'),
  ('equilibree', 'toutvabien', 'epique'),
  ('equilibree', 'eurobeat', 'epique'),
  ('equilibree', 'codevert', 'epique'),
  ('equilibree', 'flammes', 'legendaire'),
  ('equilibree', 'noiror', 'legendaire'),
  ('equilibree', 'delorean', 'legendaire'),
  ('equilibree', 'voielactee', 'legendaire'),
  ('equilibree', 'or', 'exotique'),
  ('equilibree', 'bleunitro', 'exotique'),
  ('equilibree', 'maitredrift', 'exotique'),
  ('fumee', 'rouge', 'commune'),
  ('fumee', 'bleu', 'commune'),
  ('fumee', 'rose', 'commune'),
  ('fumee', 'vert', 'commune'),
  ('fumee', 'jaune', 'commune'),
  ('fumee', 'orange', 'commune'),
  ('fumee', 'violet', 'commune'),
  ('fumee', 'noir', 'commune'),
  ('fumee', 'menthe', 'commune'),
  ('fumee', 'cendre', 'commune'),
  ('fumee', 'coucher', 'rare'),
  ('fumee', 'ocean', 'rare'),
  ('fumee', 'damier', 'rare'),
  ('fumee', 'barbapapa', 'rare'),
  ('fumee', 'ecurie', 'rare'),
  ('fumee', 'feu', 'epique'),
  ('fumee', 'toxique', 'epique'),
  ('fumee', 'neonrose', 'epique'),
  ('fumee', 'givre', 'epique'),
  ('fumee', 'arcenciel', 'legendaire'),
  ('fumee', 'galaxie', 'legendaire'),
  ('fumee', 'or', 'legendaire'),
  ('fumee', 'prisme', 'exotique'),
  ('fumee', 'aurore', 'exotique'),
  ('kei', 'rayures', 'commune'),
  ('kei', 'bicolore', 'commune'),
  ('kei', 'filet', 'commune'),
  ('kei', 'konbini', 'commune'),
  ('kei', 'minipois', 'commune'),
  ('kei', 'sakura', 'commune'),
  ('kei', 'kawaii', 'commune'),
  ('kei', 'polka', 'commune'),
  ('kei', 'vies', 'commune'),
  ('kei', 'flammettes', 'commune'),
  ('kei', 'rafistolee', 'commune'),
  ('kei', 'course', 'rare'),
  ('kei', 'coccinelle', 'rare'),
  ('kei', 'abeille', 'rare'),
  ('kei', 'meuh', 'rare'),
  ('kei', 'champi', 'rare'),
  ('kei', 'banane', 'rare'),
  ('kei', 'cartemere', 'rare'),
  ('kei', 'doge', 'rare'),
  ('kei', 'among', 'rare'),
  ('kei', 'touge', 'epique'),
  ('kei', 'levant', 'epique'),
  ('kei', 'kachow', 'epique'),
  ('kei', 'eurobeat', 'epique'),
  ('kei', 'codevert', 'epique'),
  ('kei', 'toutvabien', 'epique'),
  ('kei', 'fusee', 'legendaire'),
  ('kei', 'grilleneon', 'legendaire'),
  ('kei', 'voielactee', 'legendaire'),
  ('kei', 'or', 'exotique'),
  ('kei', 'bleunitro', 'exotique'),
  ('legere', 'bande', 'commune'),
  ('legere', 'bicolore', 'commune'),
  ('legere', 'filet', 'commune'),
  ('legere', 'dents', 'commune'),
  ('legere', 'portieres', 'commune'),
  ('legere', 'polka', 'commune'),
  ('legere', 'zebre', 'commune'),
  ('legere', 'neonbas', 'commune'),
  ('legere', 'n1', 'commune'),
  ('legere', 'vies', 'commune'),
  ('legere', 'flammettes', 'commune'),
  ('legere', 'rafistolee', 'commune'),
  ('legere', 'course', 'rare'),
  ('legere', 'taxi', 'rare'),
  ('legere', 'rallye', 'rare'),
  ('legere', 'mat', 'rare'),
  ('legere', 'tofu', 'rare'),
  ('legere', '24h', 'rare'),
  ('legere', 'doge', 'rare'),
  ('legere', 'banane', 'rare'),
  ('legere', 'fantomes', 'rare'),
  ('legere', 'meuh', 'rare'),
  ('legere', 'stonks', 'rare'),
  ('legere', 'touge', 'epique'),
  ('legere', 'eclairs', 'epique'),
  ('legere', 'degrade', 'epique'),
  ('legere', 'kachow', 'epique'),
  ('legere', 'codevert', 'epique'),
  ('legere', 'flammes', 'legendaire'),
  ('legere', 'kamikaze', 'legendaire'),
  ('legere', 'k2000', 'legendaire'),
  ('legere', 'grilleneon', 'legendaire'),
  ('legere', 'chrome', 'exotique'),
  ('muscle', 'bande', 'commune'),
  ('muscle', 'rayures', 'commune'),
  ('muscle', 'bicolore', 'commune'),
  ('muscle', 'lisere', 'commune'),
  ('muscle', 'diner', 'commune'),
  ('muscle', 'riviera', 'commune'),
  ('muscle', 'danger', 'commune'),
  ('muscle', 'peinture', 'commune'),
  ('muscle', 'flammettes', 'commune'),
  ('muscle', 'n404', 'commune'),
  ('muscle', 'kawaii', 'commune'),
  ('muscle', 'course', 'rare'),
  ('muscle', 'carbone', 'rare'),
  ('muscle', 'damier', 'rare'),
  ('muscle', 'route66', 'rare'),
  ('muscle', 'cousins', 'rare'),
  ('muscle', 'etoiles', 'rare'),
  ('muscle', 'tigre', 'rare'),
  ('muscle', 'intercepteur', 'rare'),
  ('muscle', 'stonks', 'rare'),
  ('muscle', 'vitesse', 'epique'),
  ('muscle', 'camo', 'epique'),
  ('muscle', 'possedee', 'epique'),
  ('muscle', 'motardfantome', 'epique'),
  ('muscle', 'rouille', 'epique'),
  ('muscle', 'toutvabien', 'epique'),
  ('muscle', 'flammes', 'legendaire'),
  ('muscle', 'bandit', 'legendaire'),
  ('muscle', 'k2000', 'legendaire'),
  ('muscle', 'dixsec', 'exotique'),
  ('muscle', 'famille', 'exotique'),
  ('rotative', 'bande', 'commune'),
  ('rotative', 'bicolore', 'commune'),
  ('rotative', 'filet', 'commune'),
  ('rotative', 'huile', 'commune'),
  ('rotative', 'portieres', 'commune'),
  ('rotative', 'neonbas', 'commune'),
  ('rotative', 'zebre', 'commune'),
  ('rotative', 'huitbits', 'commune'),
  ('rotative', 'sakura', 'commune'),
  ('rotative', 'flammettes', 'commune'),
  ('rotative', 'n1', 'commune'),
  ('rotative', 'course', 'rare'),
  ('rotative', 'carbone', 'rare'),
  ('rotative', 'rotor', 'rare'),
  ('rotative', 'crepuscule', 'rare'),
  ('rotative', '24h', 'rare'),
  ('rotative', 'dejavu', 'rare'),
  ('rotative', 'cartemere', 'rare'),
  ('rotative', 'tofu', 'rare'),
  ('rotative', 'nyan', 'rare'),
  ('rotative', 'touge', 'epique'),
  ('rotative', 'quatrerotors', 'epique'),
  ('rotative', 'brap', 'epique'),
  ('rotative', 'levant', 'epique'),
  ('rotative', 'eurobeat', 'epique'),
  ('rotative', 'codevert', 'epique'),
  ('rotative', 'derniere', 'legendaire'),
  ('rotative', 'grilleneon', 'legendaire'),
  ('rotative', 'voielactee', 'legendaire'),
  ('rotative', 'chrome', 'exotique'),
  ('rotative', 'maitredrift', 'exotique'),
  ('turbo', 'rayures', 'commune'),
  ('turbo', 'pois', 'commune'),
  ('turbo', 'diagonales', 'commune'),
  ('turbo', 'filet', 'commune'),
  ('turbo', 'bicolore', 'commune'),
  ('turbo', 'riviera', 'commune'),
  ('turbo', 'kawaii', 'commune'),
  ('turbo', 'zebre', 'commune'),
  ('turbo', 'danger', 'commune'),
  ('turbo', 'flammettes', 'commune'),
  ('turbo', 'n404', 'commune'),
  ('turbo', 'vies', 'commune'),
  ('turbo', 'carbone', 'rare'),
  ('turbo', 'course', 'rare'),
  ('turbo', 'damier', 'rare'),
  ('turbo', 'camo', 'rare'),
  ('turbo', 'leopard', 'rare'),
  ('turbo', 'champi', 'rare'),
  ('turbo', 'slime', 'rare'),
  ('turbo', 'eclaboussure', 'rare'),
  ('turbo', 'among', 'rare'),
  ('turbo', 'intercepteur', 'rare'),
  ('turbo', 'rallyesponsors', 'rare'),
  ('turbo', 'touge', 'epique'),
  ('turbo', 'eclairs', 'epique'),
  ('turbo', 'vitesse', 'epique'),
  ('turbo', 'eurobeat', 'epique'),
  ('turbo', 'toutvabien', 'epique'),
  ('turbo', 'flammes', 'legendaire'),
  ('turbo', 'noiror', 'legendaire'),
  ('turbo', 'grilleneon', 'legendaire'),
  ('turbo', 'voielactee', 'legendaire'),
  ('turbo', 'or', 'exotique'),
  ('turbo', 'dixsec', 'exotique'),
  ('turbo', 'famille', 'exotique')
on conflict (voiture, id) do update set rarete = excluded.rarete;

-- livrées retirées du jeu (celles de l'Atelier, « atelier-… », validées dans le jeu, ne sont jamais touchées)
delete from public.catalogue_skins
 where id not like 'atelier-%'
   and (voiture, id) not in (
  ('break', 'rayures'),
  ('break', 'bicolore'),
  ('break', 'filet'),
  ('break', 'vacances'),
  ('break', 'portieres'),
  ('break', 'riviera'),
  ('break', 'polka'),
  ('break', 'peinture'),
  ('break', 'zebre'),
  ('break', 'n1'),
  ('break', 'sakura'),
  ('break', 'boiseries'),
  ('break', 'courrier'),
  ('break', 'dalmatiens'),
  ('break', 'taxi'),
  ('break', 'mystere'),
  ('break', 'fantomes'),
  ('break', 'tofu'),
  ('break', 'urgences'),
  ('break', 'n42'),
  ('break', 'touge'),
  ('break', 'safari'),
  ('break', 'rouille'),
  ('break', 'toutvabien'),
  ('break', 'eurobeat'),
  ('break', 'codevert'),
  ('break', 'flammes'),
  ('break', 'delorean'),
  ('break', 'voielactee'),
  ('break', 'or'),
  ('break', 'famille'),
  ('equilibree', 'rayures'),
  ('equilibree', 'bicolore'),
  ('equilibree', 'lisere'),
  ('equilibree', 'panda'),
  ('equilibree', 'diagonales'),
  ('equilibree', 'riviera'),
  ('equilibree', 'polka'),
  ('equilibree', 'kawaii'),
  ('equilibree', 'danger'),
  ('equilibree', 'huitbits'),
  ('equilibree', 'peinture'),
  ('equilibree', 'n404'),
  ('equilibree', 'course'),
  ('equilibree', 'carbone'),
  ('equilibree', 'damier'),
  ('equilibree', 'pois'),
  ('equilibree', 'nyan'),
  ('equilibree', 'tigre'),
  ('equilibree', 'mystere'),
  ('equilibree', 'urgences'),
  ('equilibree', 'dejavu'),
  ('equilibree', 'n42'),
  ('equilibree', 'touge'),
  ('equilibree', 'vitesse'),
  ('equilibree', 'camo'),
  ('equilibree', 'toutvabien'),
  ('equilibree', 'eurobeat'),
  ('equilibree', 'codevert'),
  ('equilibree', 'flammes'),
  ('equilibree', 'noiror'),
  ('equilibree', 'delorean'),
  ('equilibree', 'voielactee'),
  ('equilibree', 'or'),
  ('equilibree', 'bleunitro'),
  ('equilibree', 'maitredrift'),
  ('fumee', 'rouge'),
  ('fumee', 'bleu'),
  ('fumee', 'rose'),
  ('fumee', 'vert'),
  ('fumee', 'jaune'),
  ('fumee', 'orange'),
  ('fumee', 'violet'),
  ('fumee', 'noir'),
  ('fumee', 'menthe'),
  ('fumee', 'cendre'),
  ('fumee', 'coucher'),
  ('fumee', 'ocean'),
  ('fumee', 'damier'),
  ('fumee', 'barbapapa'),
  ('fumee', 'ecurie'),
  ('fumee', 'feu'),
  ('fumee', 'toxique'),
  ('fumee', 'neonrose'),
  ('fumee', 'givre'),
  ('fumee', 'arcenciel'),
  ('fumee', 'galaxie'),
  ('fumee', 'or'),
  ('fumee', 'prisme'),
  ('fumee', 'aurore'),
  ('kei', 'rayures'),
  ('kei', 'bicolore'),
  ('kei', 'filet'),
  ('kei', 'konbini'),
  ('kei', 'minipois'),
  ('kei', 'sakura'),
  ('kei', 'kawaii'),
  ('kei', 'polka'),
  ('kei', 'vies'),
  ('kei', 'flammettes'),
  ('kei', 'rafistolee'),
  ('kei', 'course'),
  ('kei', 'coccinelle'),
  ('kei', 'abeille'),
  ('kei', 'meuh'),
  ('kei', 'champi'),
  ('kei', 'banane'),
  ('kei', 'cartemere'),
  ('kei', 'doge'),
  ('kei', 'among'),
  ('kei', 'touge'),
  ('kei', 'levant'),
  ('kei', 'kachow'),
  ('kei', 'eurobeat'),
  ('kei', 'codevert'),
  ('kei', 'toutvabien'),
  ('kei', 'fusee'),
  ('kei', 'grilleneon'),
  ('kei', 'voielactee'),
  ('kei', 'or'),
  ('kei', 'bleunitro'),
  ('legere', 'bande'),
  ('legere', 'bicolore'),
  ('legere', 'filet'),
  ('legere', 'dents'),
  ('legere', 'portieres'),
  ('legere', 'polka'),
  ('legere', 'zebre'),
  ('legere', 'neonbas'),
  ('legere', 'n1'),
  ('legere', 'vies'),
  ('legere', 'flammettes'),
  ('legere', 'rafistolee'),
  ('legere', 'course'),
  ('legere', 'taxi'),
  ('legere', 'rallye'),
  ('legere', 'mat'),
  ('legere', 'tofu'),
  ('legere', '24h'),
  ('legere', 'doge'),
  ('legere', 'banane'),
  ('legere', 'fantomes'),
  ('legere', 'meuh'),
  ('legere', 'stonks'),
  ('legere', 'touge'),
  ('legere', 'eclairs'),
  ('legere', 'degrade'),
  ('legere', 'kachow'),
  ('legere', 'codevert'),
  ('legere', 'flammes'),
  ('legere', 'kamikaze'),
  ('legere', 'k2000'),
  ('legere', 'grilleneon'),
  ('legere', 'chrome'),
  ('muscle', 'bande'),
  ('muscle', 'rayures'),
  ('muscle', 'bicolore'),
  ('muscle', 'lisere'),
  ('muscle', 'diner'),
  ('muscle', 'riviera'),
  ('muscle', 'danger'),
  ('muscle', 'peinture'),
  ('muscle', 'flammettes'),
  ('muscle', 'n404'),
  ('muscle', 'kawaii'),
  ('muscle', 'course'),
  ('muscle', 'carbone'),
  ('muscle', 'damier'),
  ('muscle', 'route66'),
  ('muscle', 'cousins'),
  ('muscle', 'etoiles'),
  ('muscle', 'tigre'),
  ('muscle', 'intercepteur'),
  ('muscle', 'stonks'),
  ('muscle', 'vitesse'),
  ('muscle', 'camo'),
  ('muscle', 'possedee'),
  ('muscle', 'motardfantome'),
  ('muscle', 'rouille'),
  ('muscle', 'toutvabien'),
  ('muscle', 'flammes'),
  ('muscle', 'bandit'),
  ('muscle', 'k2000'),
  ('muscle', 'dixsec'),
  ('muscle', 'famille'),
  ('rotative', 'bande'),
  ('rotative', 'bicolore'),
  ('rotative', 'filet'),
  ('rotative', 'huile'),
  ('rotative', 'portieres'),
  ('rotative', 'neonbas'),
  ('rotative', 'zebre'),
  ('rotative', 'huitbits'),
  ('rotative', 'sakura'),
  ('rotative', 'flammettes'),
  ('rotative', 'n1'),
  ('rotative', 'course'),
  ('rotative', 'carbone'),
  ('rotative', 'rotor'),
  ('rotative', 'crepuscule'),
  ('rotative', '24h'),
  ('rotative', 'dejavu'),
  ('rotative', 'cartemere'),
  ('rotative', 'tofu'),
  ('rotative', 'nyan'),
  ('rotative', 'touge'),
  ('rotative', 'quatrerotors'),
  ('rotative', 'brap'),
  ('rotative', 'levant'),
  ('rotative', 'eurobeat'),
  ('rotative', 'codevert'),
  ('rotative', 'derniere'),
  ('rotative', 'grilleneon'),
  ('rotative', 'voielactee'),
  ('rotative', 'chrome'),
  ('rotative', 'maitredrift'),
  ('turbo', 'rayures'),
  ('turbo', 'pois'),
  ('turbo', 'diagonales'),
  ('turbo', 'filet'),
  ('turbo', 'bicolore'),
  ('turbo', 'riviera'),
  ('turbo', 'kawaii'),
  ('turbo', 'zebre'),
  ('turbo', 'danger'),
  ('turbo', 'flammettes'),
  ('turbo', 'n404'),
  ('turbo', 'vies'),
  ('turbo', 'carbone'),
  ('turbo', 'course'),
  ('turbo', 'damier'),
  ('turbo', 'camo'),
  ('turbo', 'leopard'),
  ('turbo', 'champi'),
  ('turbo', 'slime'),
  ('turbo', 'eclaboussure'),
  ('turbo', 'among'),
  ('turbo', 'intercepteur'),
  ('turbo', 'rallyesponsors'),
  ('turbo', 'touge'),
  ('turbo', 'eclairs'),
  ('turbo', 'vitesse'),
  ('turbo', 'eurobeat'),
  ('turbo', 'toutvabien'),
  ('turbo', 'flammes'),
  ('turbo', 'noiror'),
  ('turbo', 'grilleneon'),
  ('turbo', 'voielactee'),
  ('turbo', 'or'),
  ('turbo', 'dixsec'),
  ('turbo', 'famille')
);
