-- Drift Club : catalogue des livrées qui sortent des caisses (GÉNÉRÉ, ne pas modifier à la main).
-- Produit par : npx vite-node tools/gen-catalogue-sql.ts (à partir de src/core/skins.ts).
-- À coller dans Supabase → SQL Editor → Run, après 0005. Peut être relancé sans danger.
-- Après avoir ajouté ou retiré des livrées : relancer le générateur et coller de nouveau ce fichier.
-- 45 livrées.

insert into public.catalogue_skins (voiture, id, rarete) values
  ('equilibree', 'rayures', 'commune'),
  ('equilibree', 'bicolore', 'commune'),
  ('equilibree', 'lisere', 'commune'),
  ('equilibree', 'panda', 'commune'),
  ('equilibree', 'diagonales', 'commune'),
  ('equilibree', 'course', 'rare'),
  ('equilibree', 'carbone', 'rare'),
  ('equilibree', 'damier', 'rare'),
  ('equilibree', 'pois', 'rare'),
  ('equilibree', 'touge', 'epique'),
  ('equilibree', 'vitesse', 'epique'),
  ('equilibree', 'camo', 'epique'),
  ('equilibree', 'flammes', 'legendaire'),
  ('equilibree', 'noiror', 'legendaire'),
  ('equilibree', 'or', 'exotique'),
  ('legere', 'bande', 'commune'),
  ('legere', 'bicolore', 'commune'),
  ('legere', 'filet', 'commune'),
  ('legere', 'dents', 'commune'),
  ('legere', 'portieres', 'commune'),
  ('legere', 'course', 'rare'),
  ('legere', 'taxi', 'rare'),
  ('legere', 'rallye', 'rare'),
  ('legere', 'mat', 'rare'),
  ('legere', 'touge', 'epique'),
  ('legere', 'eclairs', 'epique'),
  ('legere', 'degrade', 'epique'),
  ('legere', 'flammes', 'legendaire'),
  ('legere', 'kamikaze', 'legendaire'),
  ('legere', 'chrome', 'exotique'),
  ('turbo', 'rayures', 'commune'),
  ('turbo', 'pois', 'commune'),
  ('turbo', 'diagonales', 'commune'),
  ('turbo', 'filet', 'commune'),
  ('turbo', 'bicolore', 'commune'),
  ('turbo', 'carbone', 'rare'),
  ('turbo', 'course', 'rare'),
  ('turbo', 'damier', 'rare'),
  ('turbo', 'camo', 'rare'),
  ('turbo', 'touge', 'epique'),
  ('turbo', 'eclairs', 'epique'),
  ('turbo', 'vitesse', 'epique'),
  ('turbo', 'flammes', 'legendaire'),
  ('turbo', 'noiror', 'legendaire'),
  ('turbo', 'or', 'exotique')
on conflict (voiture, id) do update set rarete = excluded.rarete;

-- livrées retirées du jeu
delete from public.catalogue_skins
 where (voiture, id) not in (
  ('equilibree', 'rayures'),
  ('equilibree', 'bicolore'),
  ('equilibree', 'lisere'),
  ('equilibree', 'panda'),
  ('equilibree', 'diagonales'),
  ('equilibree', 'course'),
  ('equilibree', 'carbone'),
  ('equilibree', 'damier'),
  ('equilibree', 'pois'),
  ('equilibree', 'touge'),
  ('equilibree', 'vitesse'),
  ('equilibree', 'camo'),
  ('equilibree', 'flammes'),
  ('equilibree', 'noiror'),
  ('equilibree', 'or'),
  ('legere', 'bande'),
  ('legere', 'bicolore'),
  ('legere', 'filet'),
  ('legere', 'dents'),
  ('legere', 'portieres'),
  ('legere', 'course'),
  ('legere', 'taxi'),
  ('legere', 'rallye'),
  ('legere', 'mat'),
  ('legere', 'touge'),
  ('legere', 'eclairs'),
  ('legere', 'degrade'),
  ('legere', 'flammes'),
  ('legere', 'kamikaze'),
  ('legere', 'chrome'),
  ('turbo', 'rayures'),
  ('turbo', 'pois'),
  ('turbo', 'diagonales'),
  ('turbo', 'filet'),
  ('turbo', 'bicolore'),
  ('turbo', 'carbone'),
  ('turbo', 'course'),
  ('turbo', 'damier'),
  ('turbo', 'camo'),
  ('turbo', 'touge'),
  ('turbo', 'eclairs'),
  ('turbo', 'vitesse'),
  ('turbo', 'flammes'),
  ('turbo', 'noiror'),
  ('turbo', 'or')
);
