-- Drift Club : catalogue des livrées qui sortent des caisses (GÉNÉRÉ, ne pas modifier à la main).
-- Produit par : npx vite-node tools/gen-catalogue-sql.ts (à partir de src/core/skins.ts).
-- À coller dans Supabase → SQL Editor → Run, après 0005. Peut être relancé sans danger.
-- Après avoir ajouté ou retiré des livrées : relancer le générateur et coller de nouveau ce fichier.
-- 103 livrées.

insert into public.catalogue_skins (voiture, id, rarete) values
  ('equilibree', 'rayures', 'commune'),
  ('equilibree', 'bicolore', 'commune'),
  ('equilibree', 'lisere', 'commune'),
  ('equilibree', 'panda', 'commune'),
  ('equilibree', 'diagonales', 'commune'),
  ('equilibree', 'riviera', 'commune'),
  ('equilibree', 'polka', 'commune'),
  ('equilibree', 'kawaii', 'commune'),
  ('equilibree', 'danger', 'commune'),
  ('equilibree', 'huitbits', 'commune'),
  ('equilibree', 'peinture', 'commune'),
  ('equilibree', 'n404', 'commune'),
  ('equilibree', 'course', 'rare'),
  ('equilibree', 'carbone', 'rare'),
  ('equilibree', 'damier', 'rare'),
  ('equilibree', 'pois', 'rare'),
  ('equilibree', 'nyan', 'rare'),
  ('equilibree', 'tigre', 'rare'),
  ('equilibree', 'mystere', 'rare'),
  ('equilibree', 'urgences', 'rare'),
  ('equilibree', 'dejavu', 'rare'),
  ('equilibree', 'n42', 'rare'),
  ('equilibree', 'touge', 'epique'),
  ('equilibree', 'vitesse', 'epique'),
  ('equilibree', 'camo', 'epique'),
  ('equilibree', 'toutvabien', 'epique'),
  ('equilibree', 'eurobeat', 'epique'),
  ('equilibree', 'codevert', 'epique'),
  ('equilibree', 'flammes', 'legendaire'),
  ('equilibree', 'noiror', 'legendaire'),
  ('equilibree', 'delorean', 'legendaire'),
  ('equilibree', 'voielactee', 'legendaire'),
  ('equilibree', 'or', 'exotique'),
  ('equilibree', 'bleunitro', 'exotique'),
  ('equilibree', 'maitredrift', 'exotique'),
  ('legere', 'bande', 'commune'),
  ('legere', 'bicolore', 'commune'),
  ('legere', 'filet', 'commune'),
  ('legere', 'dents', 'commune'),
  ('legere', 'portieres', 'commune'),
  ('legere', 'polka', 'commune'),
  ('legere', 'zebre', 'commune'),
  ('legere', 'neonbas', 'commune'),
  ('legere', 'n1', 'commune'),
  ('legere', 'vies', 'commune'),
  ('legere', 'flammettes', 'commune'),
  ('legere', 'rafistolee', 'commune'),
  ('legere', 'course', 'rare'),
  ('legere', 'taxi', 'rare'),
  ('legere', 'rallye', 'rare'),
  ('legere', 'mat', 'rare'),
  ('legere', 'tofu', 'rare'),
  ('legere', '24h', 'rare'),
  ('legere', 'doge', 'rare'),
  ('legere', 'banane', 'rare'),
  ('legere', 'fantomes', 'rare'),
  ('legere', 'meuh', 'rare'),
  ('legere', 'stonks', 'rare'),
  ('legere', 'touge', 'epique'),
  ('legere', 'eclairs', 'epique'),
  ('legere', 'degrade', 'epique'),
  ('legere', 'kachow', 'epique'),
  ('legere', 'codevert', 'epique'),
  ('legere', 'flammes', 'legendaire'),
  ('legere', 'kamikaze', 'legendaire'),
  ('legere', 'k2000', 'legendaire'),
  ('legere', 'grilleneon', 'legendaire'),
  ('legere', 'chrome', 'exotique'),
  ('turbo', 'rayures', 'commune'),
  ('turbo', 'pois', 'commune'),
  ('turbo', 'diagonales', 'commune'),
  ('turbo', 'filet', 'commune'),
  ('turbo', 'bicolore', 'commune'),
  ('turbo', 'riviera', 'commune'),
  ('turbo', 'kawaii', 'commune'),
  ('turbo', 'zebre', 'commune'),
  ('turbo', 'danger', 'commune'),
  ('turbo', 'flammettes', 'commune'),
  ('turbo', 'n404', 'commune'),
  ('turbo', 'vies', 'commune'),
  ('turbo', 'carbone', 'rare'),
  ('turbo', 'course', 'rare'),
  ('turbo', 'damier', 'rare'),
  ('turbo', 'camo', 'rare'),
  ('turbo', 'leopard', 'rare'),
  ('turbo', 'champi', 'rare'),
  ('turbo', 'slime', 'rare'),
  ('turbo', 'eclaboussure', 'rare'),
  ('turbo', 'among', 'rare'),
  ('turbo', 'intercepteur', 'rare'),
  ('turbo', 'rallyesponsors', 'rare'),
  ('turbo', 'touge', 'epique'),
  ('turbo', 'eclairs', 'epique'),
  ('turbo', 'vitesse', 'epique'),
  ('turbo', 'eurobeat', 'epique'),
  ('turbo', 'toutvabien', 'epique'),
  ('turbo', 'flammes', 'legendaire'),
  ('turbo', 'noiror', 'legendaire'),
  ('turbo', 'grilleneon', 'legendaire'),
  ('turbo', 'voielactee', 'legendaire'),
  ('turbo', 'or', 'exotique'),
  ('turbo', 'dixsec', 'exotique'),
  ('turbo', 'famille', 'exotique')
on conflict (voiture, id) do update set rarete = excluded.rarete;

-- livrées retirées du jeu
delete from public.catalogue_skins
 where (voiture, id) not in (
  ('equilibree', 'rayures'),
  ('equilibree', 'bicolore'),
  ('equilibree', 'lisere'),
  ('equilibree', 'panda'),
  ('equilibree', 'diagonales'),
  ('equilibree', 'riviera'),
  ('equilibree', 'polka'),
  ('equilibree', 'kawaii'),
  ('equilibree', 'danger'),
  ('equilibree', 'huitbits'),
  ('equilibree', 'peinture'),
  ('equilibree', 'n404'),
  ('equilibree', 'course'),
  ('equilibree', 'carbone'),
  ('equilibree', 'damier'),
  ('equilibree', 'pois'),
  ('equilibree', 'nyan'),
  ('equilibree', 'tigre'),
  ('equilibree', 'mystere'),
  ('equilibree', 'urgences'),
  ('equilibree', 'dejavu'),
  ('equilibree', 'n42'),
  ('equilibree', 'touge'),
  ('equilibree', 'vitesse'),
  ('equilibree', 'camo'),
  ('equilibree', 'toutvabien'),
  ('equilibree', 'eurobeat'),
  ('equilibree', 'codevert'),
  ('equilibree', 'flammes'),
  ('equilibree', 'noiror'),
  ('equilibree', 'delorean'),
  ('equilibree', 'voielactee'),
  ('equilibree', 'or'),
  ('equilibree', 'bleunitro'),
  ('equilibree', 'maitredrift'),
  ('legere', 'bande'),
  ('legere', 'bicolore'),
  ('legere', 'filet'),
  ('legere', 'dents'),
  ('legere', 'portieres'),
  ('legere', 'polka'),
  ('legere', 'zebre'),
  ('legere', 'neonbas'),
  ('legere', 'n1'),
  ('legere', 'vies'),
  ('legere', 'flammettes'),
  ('legere', 'rafistolee'),
  ('legere', 'course'),
  ('legere', 'taxi'),
  ('legere', 'rallye'),
  ('legere', 'mat'),
  ('legere', 'tofu'),
  ('legere', '24h'),
  ('legere', 'doge'),
  ('legere', 'banane'),
  ('legere', 'fantomes'),
  ('legere', 'meuh'),
  ('legere', 'stonks'),
  ('legere', 'touge'),
  ('legere', 'eclairs'),
  ('legere', 'degrade'),
  ('legere', 'kachow'),
  ('legere', 'codevert'),
  ('legere', 'flammes'),
  ('legere', 'kamikaze'),
  ('legere', 'k2000'),
  ('legere', 'grilleneon'),
  ('legere', 'chrome'),
  ('turbo', 'rayures'),
  ('turbo', 'pois'),
  ('turbo', 'diagonales'),
  ('turbo', 'filet'),
  ('turbo', 'bicolore'),
  ('turbo', 'riviera'),
  ('turbo', 'kawaii'),
  ('turbo', 'zebre'),
  ('turbo', 'danger'),
  ('turbo', 'flammettes'),
  ('turbo', 'n404'),
  ('turbo', 'vies'),
  ('turbo', 'carbone'),
  ('turbo', 'course'),
  ('turbo', 'damier'),
  ('turbo', 'camo'),
  ('turbo', 'leopard'),
  ('turbo', 'champi'),
  ('turbo', 'slime'),
  ('turbo', 'eclaboussure'),
  ('turbo', 'among'),
  ('turbo', 'intercepteur'),
  ('turbo', 'rallyesponsors'),
  ('turbo', 'touge'),
  ('turbo', 'eclairs'),
  ('turbo', 'vitesse'),
  ('turbo', 'eurobeat'),
  ('turbo', 'toutvabien'),
  ('turbo', 'flammes'),
  ('turbo', 'noiror'),
  ('turbo', 'grilleneon'),
  ('turbo', 'voielactee'),
  ('turbo', 'or'),
  ('turbo', 'dixsec'),
  ('turbo', 'famille')
);
